Use [TPC];

Insert into [Item_Type] values(1,'Drikkevarer');
Insert into [Item_Type] values(2,'Pizzaer');
Insert into [Item_Type] values(3,'Indbagt Pizza');
Insert into [Item_Type] values(4,'Pastaretter');
Insert into [Item_Type] values(5,'Panino');
Insert into [Item_Type] values(6,'Sandwich');
Insert into [Item_Type] values(7,'Salater');
Insert into [Item_Type] values(8,'Grillmad');
Insert into [Item_Type] values(11,'Andet');
Insert into [Item_Type] values(12, 'Desserter');

Insert into [Item] values(,'Andet');


Insert into [Item] values(1,'Margherita');
Insert into [Size_Price] values(1,'A',50.00);
Insert into [Size_Price] values(1,'F',90.00);
Insert into [Item] values(2, 'Pepperoni');
Insert into [Size_price] values(2,'A', 68.00);
Insert into [Size_price] values(2, 'F', 110.00);
Insert into [Item] values(3, 'Quattro');
Insert into [Size_price] values(3, 'A', 66.00);
Insert into [Size_price] values(3, 'F', 110.00);
Insert into [Item] values(4, 'Capricciosa');
Insert into [Size_price] values(4, 'A', 62.00);
Insert into [Size_price] values(4, 'F', 110.00);
Insert into [Item] values(5, 'Cacciatore');
Insert into [Size_price] values(5, 'A', 70.00);
Insert into [Size_price] values(5, 'F', 116.00);
Insert into [Item] values(6, 'Italiana');
Insert into [Size_price] values(6, 'A', 62.00);
Insert into [Size_price] values(6, 'F', 110.00);
Insert into [Item] values(7, 'Vegetariana');
Insert into [Size_price] values(7, 'A', 66.00);
Insert into [Size_price] values(7, 'F', 112.00);
Insert into [Item] values(8, 'Romana');
Insert into [Size_price] values(8, 'A', 68.00);
Insert into [Size_price] values(8, 'F', 112.00);
Insert into [Item] values(9, 'Hawaii');
Insert into [Size_price] values(9, 'A', 62.00);
Insert into [Size_price] values(9, 'F', 110.00);
Insert into [Item] values(10, 'Mexicana');
Insert into [Size_price] values(10, 'A', 66.00);
Insert into [Size_price] values(10, 'F', 112.00);
Insert into [Item] values(11, 'Paesana');
Insert into [Size_price] values(11, 'A', 72.00);
Insert into [Size_price] values(11, 'F', 122.00);
Insert into [Item] values(12, 'Marinara');
Insert into [Size_price] values(12, 'A', 70.00);
Insert into [Size_price] values(12, 'F', 122.00);
Insert into [Item] values(13, 'Amore');
Insert into [Size_price] values(13, 'A', 76.00);
Insert into [Size_price] values(13, 'F', 128.00);
Insert into [Item] values(14,'Quezzi');
Insert into [Size_price] values(14, 'A', 76.00);
Insert into [Size_price] values(14, 'F', 128.00);
Insert into [Item] values(15,'Gorgonzola');
Insert into [Size_price] values(15, 'A', 76.00);
Insert into [Size_price] values(15, 'F', 128.00);
Insert into [Item] values(16,'Spinat & Gorgonzola');
Insert into [Size_price] values(16, 'A', 66.00);
Insert into [Size_price] values(16, 'F', 116.00);
Insert into [Item] values(17,'Pastrami');
Insert into [Size_price] values(17, 'A', 76.00);
Insert into [Size_price] values(17, 'F', 128.00);
Insert into [Item] values(18,'Pacone');
Insert into [Size_price] values(18, 'A', 76.00);
Insert into [Size_price] values(18, 'F', 128.00);
Insert into [Item] values(19,'Quattro Stagioni');
Insert into [Size_price] values(19, 'A', 78.00);
Insert into [Size_price] values(19, 'F', 128.00);
Insert into [Item] values(20,'Shawarma');
Insert into [Size_price] values(20, 'A', 72.00);
Insert into [Size_price] values(20, 'F', 128.00);
Insert into [Item] values(21,'Torino');
Insert into [Size_price] values(21, 'A', 76.00);
Insert into [Size_price] values(21, 'F', 128.00);
Insert into [Item] values(22,'Toscana');
Insert into [Size_price] values(22, 'A', 76.00);
Insert into [Size_price] values(22, 'F', 128.00);
Insert into [Item] values(23,'Americana');
Insert into [Size_price] values(23, 'A', 76.00);
Insert into [Size_price] values(23, 'F', 128.00);
Insert into [Item] values(24,'Pollo');
Insert into [Size_price] values(24, 'A', 70.00);
Insert into [Size_price] values(24, 'F', 126.00);
Insert into [Item] values(25,'Diavola');
Insert into [Size_price] values(25, 'A', 70.00);
Insert into [Size_price] values(25, 'F', 112.00);
Insert into [Item] values(26,'Pollo & Rucola');
Insert into [Size_price] values(26, 'A', 72.00);
Insert into [Size_price] values(26, 'F', 114.00);
Insert into [Item] values(27,'Mortadella & Rucola');
Insert into [Size_price] values(27, 'A', 75.00);
Insert into [Size_price] values(27, 'F', 128.00);
Insert into [Item] values(28,'Vecchia');
Insert into [Size_price] values(28, 'A', 70.00);
Insert into [Size_price] values(28, 'F', 122.00);
Insert into [Item] values(29,'Pesto');
Insert into [Size_price] values(29, 'A', 72.00);
Insert into [Size_price] values(29, 'F', 124.00);
Insert into [Item] values(30,'Pollo Pesto');
Insert into [Size_price] values(30, 'A', 72.00);
Insert into [Size_price] values(30, 'F', 126.00);
Insert into [Item] values(31,' Bianca');
Insert into [Size_price] values(31, 'A', 72.00);
Insert into [Size_price] values(31, 'F', 126.00);
Insert into [Item] values(32,'Emiliana');
Insert into [Size_price] values(32, 'A', 74.00);
Insert into [Size_price] values(32, 'F', 126.00);
Insert into [Item] values(33,'Al Tramonto');
Insert into [Size_price] values(33, 'A', 76.00);
Insert into [Size_price] values(33, 'F', 128.00);
Insert into [Item] values(34,'Bresaola');
Insert into [Size_price] values(34, 'A', 76.00);
Insert into [Size_price] values(34, 'F', 128.00);
Insert into [Item] values(35,'Vattoria');
Insert into [Size_price] values(35, 'A', 74.00);
Insert into [Size_price] values(35, 'F', 126.00);
Insert into [Item] values(36,'Serena');
Insert into [Size_price] values(36, 'A', 76.00);
Insert into [Size_price] values(36, 'F', 128.00);
Insert into [Item] values(37,'Amalfi');
Insert into [Size_price] values(37, 'A', 76.00);
Insert into [Size_price] values(37, 'F', 128.00);
Insert into [Item] values(38,'Alfredo');
Insert into [Size_price] values(38, 'A', 78.00);
Insert into [Size_price] values(38, 'F', 130.00);
Insert into [Item] values(39,'Claudio');
Insert into [Size_price] values(39, 'A', 78.00);
Insert into [Size_price] values(39, 'F', 130.00);
Insert into [Item] values(40,'Sole Di Modena');
Insert into [Size_price] values(40, 'A', 78.00);
Insert into [Size_price] values(40, 'F', 130.00);
Insert into [Item] values(41,'Al Salmone');
Insert into [Size_price] values(41, 'A', 76.00);
Insert into [Size_price] values(41, 'F', 128.00);
Insert into [Item] values(42,'Milano');
Insert into [Size_price] values(42, 'A', 76.00);
Insert into [Size_price] values(42, 'F', 128.00);
Insert into [Item] values(43,'Mama Mia');
Insert into [Size_price] values(43, 'A', 80.00);
Insert into [Size_price] values(43, 'F', 132.00);
Insert into [Item] values(45,'Børnepizza - Bacon');
Insert into [Size_price] values(45, 'B', 44.00);
Insert into [Item] values(46,'Børnepizza - Pepperoni');
Insert into [Size_price] values(46, 'B', 44.00);
Insert into [Item] values(47,'Børnepizza - Skinke');
Insert into [Size_price] values(47, 'B', 44.00);
Insert into [Item] values(44,'Riva');
Insert into [Size_price] values(44, 'A', 76.00);
Insert into [Size_price] values(44, 'F', 128.00);
Insert into [Item] values(50,'Moniga');
Insert into [Size_price] values(50, 'A', 82.00);
Insert into [Size_price] values(50, 'F', 136.00);
Insert into [Item] values(51,'Vitello');
Insert into [Size_price] values(51, 'A', 75.00);
Insert into [Size_price] values(51, 'F', 126.00);
Insert into [Item] values(52,'Ginova');
Insert into [Size_price] values(52, 'A', 80.00);
Insert into [Size_price] values(52, 'F', 132.00);
Insert into [Item] values(53,'Lago');
Insert into [Size_price] values(53, 'A', 82.00);
Insert into [Size_price] values(53, 'F', 134.00);
Insert into [Item] values(54,'2-Delt Familiepizza');
Insert into [Size_price] values(54, 'F', 130.00);
