USE TPC;

Insert into [Ingrediens] values(0, '4 forskellige slags ost');
Insert into [Ingrediens] values(1, 'tomat');
Insert into [Ingrediens] values(2, 'ost');
Insert into [Ingrediens] values(3, 'skinke');
Insert into [Ingrediens] values(4, 'pepperoni');
Insert into [Ingrediens] values(5, 'paprika');
Insert into [Ingrediens] values(6, 'champignon');
Insert into [Ingrediens] values(7, 'oliven');
Insert into [Ingrediens] values(8, 'bacon');
Insert into [Ingrediens] values(9, 'l�g');
Insert into [Ingrediens] values(10, 'k�dsauce');
Insert into [Ingrediens] values(11, 'asparges');
Insert into [Ingrediens] values(12, 'artiskok');
Insert into [Ingrediens] values(13, 'paberfrugt');
Insert into [Ingrediens] values(14, '�g');
Insert into [Ingrediens] values(15, 'ananas');
Insert into [Ingrediens] values(16, 'chilisauce');
Insert into [Ingrediens] values(17, 'karry');
Insert into [Ingrediens] values(18, 'kylling');
Insert into [Ingrediens] values(19, 'rejer');
Insert into [Ingrediens] values(20, 'tun');
Insert into [Ingrediens] values(21, 'frisk tomat');
Insert into [Ingrediens] values(22, 'spinat');
Insert into [Ingrediens] values(23, 'parmaskinke');
Insert into [Ingrediens] values(24, 'gorgonzola');
Insert into [Ingrediens] values(25, 'pastrami');
Insert into [Ingrediens] values(26, 'salat');
Insert into [Ingrediens] values(27, 'k�dfars');
Insert into [Ingrediens] values(28, 'katoffelskiver');
Insert into [Ingrediens] values(29, 'k�dstrimler');
Insert into [Ingrediens] values(30, 'pesto');
Insert into [Ingrediens] values(31, 'rucola');
Insert into [Ingrediens] values(32, 'mortadellap�lse');
Insert into [Ingrediens] values(33, 'italiensk salami');
Insert into [Ingrediens] values(34, 'fetaost');
Insert into [Ingrediens] values(35, 'hjemmelavet pesto');
Insert into [Ingrediens] values(36, 'rosmarin');
Insert into [Ingrediens] values(37, 'bresaola');
Insert into [Ingrediens] values(38, 'grillede auberginer');
Insert into [Ingrediens] values(39, 'jalapenos');
Insert into [Ingrediens] values(40, 'squash');
Insert into [Ingrediens] values(41, 'pecorino ost');
Insert into [Ingrediens] values(42, 'solt�rrede tomater');
Insert into [Ingrediens] values(43, 'r�get laks');
Insert into [Ingrediens] values(44, 'panchita');
Insert into [Ingrediens] values(45, 'laks');
Insert into [Ingrediens] values(46, 'mascarpone');
Insert into [Ingrediens] values(47, 'vitello (tynde skiver kalvek�d)');
Insert into [Ingrediens] values(48, 'tr�ffelsauce');
Insert into [Ingrediens] values(49, 'kartofler');
Insert into [Ingrediens] values(50, 'cherrytomater');
Insert into [Ingrediens] values(51, 'parmesanost');
Insert into [Ingrediens] values(52, 'kapers');
Insert into [Ingrediens] values(53, 'salami');

Insert into [Ingrediens] values(54, 'spaghetti');

Insert into [Ingrediens] values(55, 'fl�desauce');
Insert into [Ingrediens] values(56, 'b�ndspaghetti');
Insert into [Ingrediens] values(57, '�rter');
Insert into [Ingrediens] values(58, 'gorgonzolasauce');
Insert into [Ingrediens] values(59, 'tortellini');
Insert into [Ingrediens] values(60, 'gratineret ravioli');
Insert into [Ingrediens] values(61, 'ost (ovnbagt)');
Insert into [Ingrediens] values(62, 'basilikum');
Insert into [Ingrediens] values(63, 'klassisk pastarulle');
Insert into [Ingrediens] values(64, 'k�dsauceefyld');
Insert into [Ingrediens] values(65, 'ragattoni');
Insert into [Ingrediens] values(66, 'fl�de');
Insert into [Ingrediens] values(67, 'tren af parmaskinke');
Insert into [Ingrediens] values(68, 'skovsvampe');
Insert into [Ingrediens] values(69, 'kalvek�d');
Insert into [Ingrediens] values(70, 'dressing');
Insert into [Ingrediens] values(71, 'agurk');
Insert into [Ingrediens] values(72, 'mozzarella');
Insert into [Ingrediens] values(74, 'majs');
Insert into [Ingrediens] values(75, 'olivenolie');
Insert into [Ingrediens] values(76, 'oregano');
Insert into [Ingrediens] values(77, 'hvidl�gsbr�d');
Insert into [Ingrediens] values(78, 'shawarma');
Insert into [Ingrediens] values(79, 'gr�n peber');
Insert into [Ingrediens] values(80, 'broccoli');
Insert into [ingrediens] values(81, 'parmasanost');
Insert into [ingrediens] values(82, 'trøffel');
insert into [ingrediens] values(83, 'ovnbagt pasta');

Insert into [Ingrediens] values(101, 'perroni morretti');

Insert into [Ingrediens] values(151, 'i b�ger');

Insert into [Ingrediens] values(1001, '1 stk. med familiepizza bestående af 2 forskellige pizzaer');
